COLUMNS_CURATED = {
    'Número da Proposta': 'cd_proposta',
    'Número Contrato para Administração': 'cd_contrato_admin',
    'Situação': 'dc_situacao',
    'Etapa': 'dc_etapa',
    'Item de Produto': 'dc_produto',
    'CPF do Proponente': 'cpf_proponente',
    'Código do Proponente (COCLI)': 'cd_proponente',
    'Nome do Proponente': 'nome_proponente',
    'Data de Nascimento': 'dt_nascimento_proponente',
    'Unidade/Célula/Responsável': 'cd_unidade_responsavel',
    'Código da Avaliação': 'cd_avaliacao',
    'Avaliação do Imóvel': 'vl_avaliacao_imovel',
    'Cota de Financiamento': 'perc_cota_financiamento',
    'Valor do Financiamento': 'vl_financiamento',
    'Prestação Máxima': 'vl_prestacao_maxima',
    'Data da Avaliação': 'dt_avaliacao',
    'Validade da Avaliação de Risco do Cliente': 'dt_validade_avaliacao',
    'Avaliação Consignada': 'fl_avaliacao_consignida',
    'Avaliação Convênio Bahia': 'fl_avaliacao_convenio_bahia',
    'Rating': 'dc_rating',
    'Sistema de Amortização': 'dc_sistema_amortizacao',
    'Índice Governamental': 'dc_indice_governamental',
    'Conceito da Operação': 'dc_conceito_operacao',
    'Valor de Financiamento Autorizado': 'vl_financiamento_autorizado',
    'Prazo de Financiamento Autorizado': 'prazo_financiamento_autorizado',
    'Valor do Encargo': 'vl_encargo',
    'Validade da Avaliação': 'dt_validade_avaliacao',
    'Unidade Solicitante': 'cd_unidade_solicitante',
    'Responsável pela Operação': 'dc_responsavel_operacao',
    'Tipo da Garantia': 'tp_avaliacao',
    'Valor da Garantia': 'vl_garantia',
    'Data/Hora da Criação': 'dt_criacao',
    'GRH': 'cd_grh',
    'Número APF/CER': 'nr_apf_cer',
    'Fonte de Recurso': 'dc_fonte_recurso',
    'Tipo de Financiamento': 'tp_financiamento',
    'Correspondente Caixa Aqui': 'cd_correspondente_caixa_aqui',
    'Código da Reserva': 'cd_reserva',
    'Seguradora': 'dc_seguradora',
    'Data do Agendamento da Assinatura do Contrato': 'dt_agendamento_assinatura_contrato',
    'Data Limite do Agendamento da Assinatura': 'dt_limite_agendamento_assinatura',
    'Altera Data de Vencimento Alterada do Primeiro Encargo?': 'fl_altera_data_vencimento_prim_encargo',
    'Data de Vencimento do Primeiro Encargo': 'dt_vencimento_prim_encargo',
    'Data de Vencimento Alterada': 'dt_vencimento_alterada',
    'Unidade de Origem': 'dc_unidade_origem',
    'Unidade de Cobrança': 'dc_unidade_cobranca',
    'Código de Exceção': 'cd_excecao',
    'Código de Legislação': 'cd_legislacao',
    'Situação Especial': 'dc_situacao_especial',
    'Possui mais de um comprador na proposta e/ou possui dependente': 'fl_possui_outro_comprador_dependente',
    'Apólice': 'dc_apolice',
    'Forma de pagamento do encargo': 'dc_forma_pagamento_encargo',
    'Deseja receber boleto impresso?': 'fl_boleto_impresso',
    'Destino do boleto': 'dc_destino_boleto',
    'Endereço para envio de outras correspondências (quitação anual, IR, etc.)': 'ed_correspondencia',
    'Regência Crítica': 'cd_regencia_critica',
    'Regência de Evolução': 'cd_regencia_evolucao',
    'Situação Interface Administração': 'dc_situacao_admin',
    'COCLI': 'cd_cocli',
    'CPF': 'cpf_comprador',
    'Nome': 'dc_comprador',
    'Sexo': 'dc_sexo',
    'Estado Civil SICLI': 'dc_estado_civil_sicli',
    'Estado Civil': 'dc_estado_civil',
    'Nacionalidade': 'dc_nacionalidade',
    'Profissão': 'dc_profissao',
    'Ocupação': 'dc_ocupacao',
    'Segmento/Carteira': 'cd_segmento_carteira',
    'Regime de Casamento': 'dc_regime_casamento',
    'Tipo de Identificação': 'tp_identificacao',
    'Órgão Expedidor': 'dc_orgao_expedidor',
    'Número': 'dc_numero',
    'UF Emissora': 'dc_uf_emissora',
    'Data Expedição': 'dt_expedicao',
    'Telefone Residencial': 'dc_telefone_comercial',
    'Telefone Comercial': 'dc_telefone_comercial',
    'Telefone Celular': 'dc_telefone_celular',
    'E-mail': 'dc_email',
    'Já foi beneficiado com subsídio do FGTS?': 'fl_beneficiado_subsidio_fgts',
    'Possui conta no FGTS há mais de 03 anos e atende aos requisitos necessários?': 'fl_conta_fgts_03_anos_com_requisitos',
    'Matrícula Empregado CAIXA': 'dc_matricula_empregado_caixa',
    'Série': 'dc_serie',
    'UF': 'cd_uf',
    'PIS/PASEP': 'cd_pis_pasep',
    'Renda Comprovada': 'vl_renda_comprovada',
    'Renda não Comprovada': 'vl_renda_nao_comprovada',
    'Percentual de Renda para Fins Securitários': 'vl_percentual_renda_fins_securitario',
    'Percentual de Renda para Fins de Convênios': 'vl_percentual_renda_fins_convenio',
    'Renda Total Apurada': 'vl_renda_total',
    'Conta para Crédito': 'cd_conta_credito',
    'Conta para Débito': 'cd_conta_debito',
    'Débito em Conta': 'dc_debito_conta',
    'Período de utilização do débito em conta': 'dc_periodo_debito_conta',
    'Autoriza débito sobre limite crédito rotativo': 'dc_autoriza_debito_sobre_limite_credito_rotativo',
    'Período de utilização do débito sobre limite crédito rotativo': 'dc_periodo_debito_sobre_limite_credito_rotativo',
    'Tipo de Logradouro': 'tp_logradouro',
    'Logradouro': 'dc_logradouro',
    'Complemento': 'dc_complemento',
    'Bairro': 'dc_bairro',
    'Município': 'dc_municipio',
    'CEP': 'dc_cep',
    'Endereço de correspondência diferente do Imóvel': 'dc_endereco_diferente_correspondencia',
    'Número da proposta de Empreendimento': 'cd_proposta_imovel',
    'Nome do Empreendimento': 'dc_empreendimento',
    'Tipo de Unidade': 'tp_unidade',
    'Endereço da Unidade Habitacional': 'ed_unidade_habitacional',
    'Vagas de Garagem': 'nr_vagas_garagem',
    'Quantidade de Dormitórios': 'nr_dormitorios',
    'Descrição da Unidade Habitacional': 'dc_unidade_habitacional',
    'Pesquisa Realizada por': 'dc_pesquisa_realizada',
    'Situação da Pesquisa': 'dc_situacao_pesquisa',
    'Resultado da Pesquisa': 'dc_resultado_pesquisa',
    'Data de Validade da Pesquisa': 'dt_validade_pesquisa',
    'Autorizada por': 'dc_autorizada_por',
    'Prazo de Amortização Negociado (meses)': 'prazo_amortizacao_negociado',
    'Taxa de Juros Variável': 'vl_taxa_juros_variavel',
    'Valor Compra e Venda ou Orçamento Proposto pelo Cliente': 'vl_compra_venda_proposto_cliente',
    'Valor Financiamento Negociado': 'vl_financiamento_negociado',
    'Cota de Financiamento Calculada': 'vl_cota_financiamento_calculada',
    'Subsídio Complemento Capacidade Financeira': 'vl_subsidio_complemento',
    'Valor Operação': 'vl_operacao',
    'Taxa de Administração Mensal': 'vl_taxa_admin_mensal',
    'Utiliza FGTS?': 'fl_utiliza_fgts',
    'Valor Recursos Próprios': 'vl_recurso_proprio',
    'Valor Fundo Garantidor PMCMV Total': 'vl_fundo_garantidor_pmcmv',
    'Taxa Efetiva': 'vl_taxa_efetiva',
    'Taxa Nominal': 'vl_taxa_nominal',
    'Encargo Mensal': 'vl_encargo_mensal',
    'Parcela de Amortização Mensal': 'vl_parcela_amortizacao',
    'Parcela de Juros Mensal': 'vl_parcela_juros',
    'Seguro DFI': 'vl_seguro_dfi',
    'Seguro MIP': 'vl_seguro_mip',
    'Prestação Efetiva Mensal': 'vl_prestacao_efetiva',
    'Percentual Redutor da Taxa de Juros': 'vl_percentual_redutor_taxa_juros',
    'Valor das Taxas Financiadas': 'vl_taxas_financiadas',
    'Taxas à vista': 'vl_taxas_avista',
    'Valor Subvenção Entrada': 'vl_subvencao_entrada',
    'Valor Subvenção Taxa': 'vl_subvencao_taxa',
    'Valor Reserva': 'vl_reserva',
    'Valor Subsídio': 'vl_subsidio',
    'Valor Diferencial de Juros': 'vl_diferencial_juros',
    'Taxa de Administração(TA)': 'vl_taxa_admin',
    'Validade da Reserva': 'dt_validade_reserva',
    'Situação da Reserva': 'dc_situacao_reserva',
    'Nº Sequencial': 'nr_sequencial',
    'Data e hora do registro do parecer': 'dt_registro_parecer',
    'Resultado': 'dc_resultado',
    'Considerações': 'dc_consideracoes',
    'Responsável': 'cd_responsavel',
    'N° da Proposta': 'cd_proposta',
    'N° do Contrato': 'cd_contrato',
    'Produto': 'dc_produto',
    'Unidade Responsável': 'dc_unidade_responsavel_',
    'Sistema de Administração': 'dc_sistema_administracao',
    'ID': 'id',
    'Nome Arquivo': 'nome_arquivo'
}


COLUMNS_ANALYTICS = {
    "id": str,
    "tp_unidade": str,
    "cd_proposta": str,
    "cd_contrato_admin": str,
    "dc_situacao": str,
    "dc_etapa": str,
    "cpf_proponente": str,
    "cd_proponente": str,
    "nome_proponente": str,
    "dt_nascimento_proponente": str,
    "cd_unidade_responsavel": str,
    "cd_avaliacao": int,
    "vl_avaliacao_imovel": float,
    "perc_cota_financiamento": float,
    "vl_financiamento": float,
    "vl_prestacao_maxima": float,
    "dt_avaliacao": str,
    "dt_validade_avaliacao": str,
    "fl_avaliacao_consignida": str,
    "fl_avaliacao_convenio_bahia": str,
    "dc_rating": str,
    "dc_sistema_amortizacao": str,
    "dc_indice_governamental": str,
    "dc_conceito_operacao": str,
    "vl_financiamento_autorizado": float,
    "prazo_financiamento_autorizado": float,
    "vl_encargo": float,
    "cd_unidade_solicitante": str,
    "dc_responsavel_operacao": str,
    "tp_avaliacao": str,
    "vl_garantia": float,
    "dt_criacao": str,
    "cd_grh": str,
    "nr_apf_cer": str,
    "dc_fonte_recurso": str,
    "tp_financiamento": str,
    "cd_correspondente_caixa_aqui": str,
    "cd_reserva": str,
    "dc_seguradora": str,
    "dt_agendamento_assinatura_contrato": str,
    "dt_limite_agendamento_assinatura": str,
    "fl_altera_data_vencimento_prim_encargo": str,
    "dt_vencimento_prim_encargo": str,
    "dt_vencimento_alterada": str,
    "dc_unidade_origem": str,
    "dc_unidade_cobranca": str,
    "cd_excecao": float,
    "cd_legislacao": float,
    "dc_situacao_especial": str,
    "fl_possui_outro_comprador_dependente": str,
    "dc_apolice": str,
    "dc_forma_pagamento_encargo": str,
    "fl_boleto_impresso": str,
    "dc_destino_boleto": str,
    "ed_correspondencia": str,
    "cd_regencia_critica": int,
    "cd_regencia_evolucao": int,
    "dc_situacao_admin": str,
    "cd_cocli": str,
    "dc_sexo": str,
    "dc_estado_civil_sicli": str,
    "dc_estado_civil": str,
    "dc_nacionalidade": str,
    "dc_profissao": str,
    "dc_ocupacao": str,
    "cd_segmento_carteira": str,
    "dc_regime_casamento": str,
    "tp_identificacao": str,
    "dc_orgao_expedidor": str,
    "dc_numero": str,
    "dc_uf_emissora": str,
    "dt_expedicao": str,
    "dc_telefone_comercial": str,
    "dc_telefone_celular": str,
    "dc_email": str,
    "fl_beneficiado_subsidio_fgts": str,
    "fl_conta_fgts_03_anos_com_requisitos": str,
    "dc_matricula_empregado_caixa": str,
    "dc_serie": str,
    "cd_uf": str,
    "cd_pis_pasep": str,
    "vl_renda_comprovada":float,
    "vl_renda_nao_comprovada": float,
    "vl_percentual_renda_fins_securitario": float,
    "vl_percentual_renda_fins_convenio": float,
    "vl_renda_total": float,
    "tp_logradouro": str,
    "dc_logradouro": str,
    "dc_complemento": str,
    "dc_bairro": str,
    "dc_municipio": str,
    "dc_cep": str,
    "dc_endereco_diferente_correspondencia": str,
    "cd_proposta_imovel": str,
    "dc_empreendimento": str,
    "ed_unidade_habitacional": str,
    "nr_vagas_garagem": int,
    "nr_dormitorios": int,
    "dc_unidade_habitacional": str,
    "dc_pesquisa_realizada": str,
    "dc_situacao_pesquisa": str,
    "dc_resultado_pesquisa": str,
    "dt_validade_pesquisa": str,
    "dc_autorizada_por": str,
    "prazo_amortizacao_negociado": int,
    "vl_taxa_juros_variavel": float,
    "vl_compra_venda_proposto_cliente": float,
    "vl_financiamento_negociado": float,
    "vl_subsidio_complemento": float,
    "vl_operacao": float,
    "vl_taxa_admin_mensal": float,
    "fl_utiliza_fgts": str,
    "vl_recurso_proprio": float,
    "vl_fundo_garantidor_pmcmv": float,
    "vl_taxa_efetiva": float,
    "vl_taxa_nominal": float,
    "vl_encargo_mensal": float,
    "vl_parcela_amortizacao": float,
    "vl_parcela_juros": float,
    "vl_seguro_dfi": float,
    "vl_seguro_mip": float,
    "vl_prestacao_efetiva": float,
    "vl_percentual_redutor_taxa_juros": float,
    "vl_taxas_financiadas": float,
    "vl_taxas_avista": float,
    "vl_subvencao_entrada": float,
    "vl_subvencao_taxa": float,
    "vl_reserva": float,
    "vl_subsidio": float,
    "vl_diferencial_juros": float,
    "vl_taxa_admin": float,
    "dt_validade_reserva": str,
    "dc_situacao_reserva": str,
    "nr_sequencial": int,
    "dt_registro_parecer": str,
    "dc_resultado": str,
    "dc_consideracoes": str,
    "cd_responsavel": str,
    "cd_contrato": str,
    "dc_sistema_amortizacao": str,
}

float_columns = [
    "vl_avaliacao_imovel",
    "vl_financiamento",
    "vl_prestacao_maxima",
    "vl_financiamento_autorizado",
    "vl_encargo",
    "vl_garantia",
    "vl_renda_comprovada",
    "vl_renda_nao_comprovada",
    "vl_renda_total",
    "vl_taxa_juros_variavel",
    "vl_compra_venda_proposto_cliente",
    "vl_financiamento_negociado",
    "vl_subsidio_complemento",
    "vl_operacao",
    "vl_taxa_admin_mensal",
    "vl_recurso_proprio",
    "vl_fundo_garantidor_pmcmv",
    "vl_taxa_efetiva",
    "vl_encargo_mensal",
    "vl_parcela_amortizacao",
    "vl_parcela_juros",
    "vl_seguro_dfi",
    "vl_seguro_mip",
    "vl_prestacao_efetiva",
    "vl_taxas_financiadas",
    "vl_taxas_avista",
    "vl_subvencao_entrada",
    "vl_subvencao_taxa",
    "vl_reserva",
    "vl_subsidio",
    "vl_diferencial_juros",
    "vl_taxa_admin",
]

percentage_columns = [
    "perc_cota_financiamento",
    "vl_percentual_renda_fins_securitario",
    "vl_percentual_renda_fins_convenio",
    "vl_percentual_redutor_taxa_juros",
    "vl_taxa_efetiva",
    "vl_taxa_nominal",
]

categories_columns = [
    "tp_avaliacao",
    "tp_financiamento",
    "dc_situacao_admin",
]